version: '3.8'

services:
  tiktok-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiktok-scraper
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Airtable Configuration
      - AIRTABLE_PAT=${AIRTABLE_PAT}
      - AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
      # Google Gemini API
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Proxy Configuration (optional)
      - PROXY=${PROXY:-}
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=${LOG_FILE:-scraper_logs.log}
      # System Configuration
      - MAX_CONCURRENT_THREADS=${MAX_CONCURRENT_THREADS:-3}
      - DEFAULT_PROFILES_PER_HASHTAG=${DEFAULT_PROFILES_PER_HASHTAG:-500}
      # Chrome/Selenium Configuration
      - CHROME_HEADLESS=true
      - CHROME_NO_SANDBOX=true
      - CHROME_DISABLE_DEV_SHM_USAGE=true
    volumes:
      # Application logs
      - ./logs:/app/logs
      # Downloaded files
      - ./downloads:/app/downloads
      # Chrome user data (for persistence)
      - chrome-data:/app/chrome-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

volumes:
  chrome-data:
    driver: local

networks:
  default:
    driver: bridge
